version: "3.9"

networks:
  web:
    external: true

services:
  iran:
    image: v2fly/v2fly-core
    container_name: "proxy_iran"
    volumes:
      - "./config.json:/etc/v2ray/config.json"
    expose:
      - 8080
    labels:
      - "traefik.enable=false"
    networks:
      web:
        ipv4_address: 10.50.0.192